# This docker-compose is used for staging purposes only, to test local build in container
version: '3.7'
services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    volumes:
      - ./staging_volumes:/mongodb/data/db
    ports:
      - 27018:27017
    expose:
     - 27018

  redis:
    image: redis:alpine
    container_name: redis_andresjordan_betest
    ports:
      - '6379:6379'

  user_services:
    container_name: ms-andresjordan-betest
    build:
      context: .
      dockerfile: Dockerfile
      target: node-ts-base
    depends_on:
      - mongodb
      - redis
    ports:
      - '4321:4321'
    volumes:
      - ./src:/myapp/src
      - ./nodemon.json:/myapp/nodemon.json
    links:
      - redis
    env_file: .env
    environment: 
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379/0
      - DB_LOCAL_CONN_STRING=mongodb://mongodb:27017/db_andresjordan_betest
    command: ["npm", "run", "dev"]